name: "Terraform Module Validation"
on: [push, pull_request]
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get terraform version variable
        run: source ../terraform.env
      - name: Setup terraform version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${TERRAFORM_VERSION}
      - name: Run terraform init and validate to test module
        run: |
          terraform init
          terraform validate
